# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-20 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UPCProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodid', models.BigIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('extra_fields', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
